CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS channels (
  id VARCHAR(64) PRIMARY KEY,
  channel_number INT UNIQUE NOT NULL,
  channel_name VARCHAR(255) NOT NULL,
  category VARCHAR(100) NOT NULL DEFAULT 'General',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS segments (
  id VARCHAR(64) PRIMARY KEY,
  channel_id VARCHAR(64) NOT NULL REFERENCES channels(id) ON DELETE CASCADE,
  title VARCHAR(255) NOT NULL,
  creator_name VARCHAR(255) NOT NULL DEFAULT 'Unknown',
  type VARCHAR(32) NOT NULL CHECK (type IN ('SHOW', 'CREATOR_PROMO', 'STATION_ID', 'INTERLUDE')),
  video_url TEXT NOT NULL,
  duration_seconds INT NOT NULL CHECK (duration_seconds > 0),
  slot_order INT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS creator_invites (
  id VARCHAR(64) PRIMARY KEY,
  token VARCHAR(128) UNIQUE NOT NULL,
  creator_name VARCHAR(255) NOT NULL,
  creator_email VARCHAR(255) NOT NULL,
  is_used BOOLEAN DEFAULT FALSE,
  expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS viewer_analytics (
  id SERIAL PRIMARY KEY,
  channel_id VARCHAR(64) REFERENCES channels(id) ON DELETE SET NULL,
  segment_id VARCHAR(64) REFERENCES segments(id) ON DELETE SET NULL,
  viewer_id VARCHAR(128) NOT NULL,
  watch_time_seconds INT DEFAULT 0,
  switched_from_channel_id VARCHAR(64),
  timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
