import type { GlobalCompanyNode } from "./types";

/** Sandbox collection nodes — no live DSP/PRO credentials required. */
export const DEFAULT_GLOBAL_COMPANY_NODES: readonly GlobalCompanyNode[] = [
  {
    companyId: "META_RIGHTS_MGR",
    name: "Meta Platforms (FB/IG Reels)",
    category: "SOCIAL_UGC",
    supportedCodes: ["isrc", "iswc", "nilId"],
    apiProtocol: "RIGHTS_MANAGER_API",
    status: "ACTIVE",
  },
  {
    companyId: "YOUTUBE_CONTENT_ID",
    name: "Google / YouTube Content ID",
    category: "SOCIAL_UGC",
    supportedCodes: ["isrc", "iswc", "isan"],
    apiProtocol: "DIRECT_REST",
    status: "ACTIVE",
  },
  {
    companyId: "BYTEDANCE_TIKTOK",
    name: "TikTok / ByteDance Sound Match",
    category: "SOCIAL_UGC",
    supportedCodes: ["isrc", "iswc"],
    apiProtocol: "RIGHTS_MANAGER_API",
    status: "ACTIVE",
  },
  {
    companyId: "SNAPCHAT_RIGHTS",
    name: "Snapchat Sounds",
    category: "SOCIAL_UGC",
    supportedCodes: ["isrc", "iswc"],
    apiProtocol: "DIRECT_REST",
    status: "ACTIVE",
  },
  {
    companyId: "SPOTIFY_DIRECT",
    name: "Spotify AB",
    category: "STREAMING_DSP",
    supportedCodes: ["isrc", "upc"],
    apiProtocol: "DDEX_ERN",
    status: "ACTIVE",
  },
  {
    companyId: "APPLE_MUSIC",
    name: "Apple Music / iTunes",
    category: "STREAMING_DSP",
    supportedCodes: ["isrc", "upc"],
    apiProtocol: "DDEX_ERN",
    status: "ACTIVE",
  },
  {
    companyId: "AMAZON_MUSIC",
    name: "Amazon Music",
    category: "STREAMING_DSP",
    supportedCodes: ["isrc", "upc"],
    apiProtocol: "DDEX_ERN",
    status: "ACTIVE",
  },
  {
    companyId: "TIDAL_DIRECT",
    name: "Tidal Platform",
    category: "STREAMING_DSP",
    supportedCodes: ["isrc", "upc"],
    apiProtocol: "DDEX_ERN",
    status: "ACTIVE",
  },
  {
    companyId: "THE_MLC_US",
    name: "The Mechanical Licensing Collective",
    category: "PRO_COLLECTION_SOCIETY",
    supportedCodes: ["iswc", "ipi"],
    apiProtocol: "DIRECT_REST",
    status: "ACTIVE",
  },
  {
    companyId: "SOUNDEXCHANGE_US",
    name: "SoundExchange Digital Performance",
    category: "PRO_COLLECTION_SOCIETY",
    supportedCodes: ["isrc", "ipn", "isni"],
    apiProtocol: "DIRECT_REST",
    status: "ACTIVE",
  },
  {
    companyId: "ASCAP_BMI_US",
    name: "ASCAP / BMI Performance Rights",
    category: "PRO_COLLECTION_SOCIETY",
    supportedCodes: ["iswc", "ipi"],
    apiProtocol: "CWR_PROTOCOL",
    status: "ACTIVE",
  },
  {
    companyId: "PRS_MCPS_UK",
    name: "PRS for Music / MCPS (UK)",
    category: "PRO_COLLECTION_SOCIETY",
    supportedCodes: ["iswc", "isrc", "ipi"],
    apiProtocol: "CWR_PROTOCOL",
    status: "ACTIVE",
  },
  {
    companyId: "SACEM_FR",
    name: "SACEM Global Clearing (France)",
    category: "PRO_COLLECTION_SOCIETY",
    supportedCodes: ["iswc", "ipi"],
    apiProtocol: "CWR_PROTOCOL",
    status: "ACTIVE",
  },
  {
    companyId: "GEMA_DE",
    name: "GEMA Mechanical & Performance (Germany)",
    category: "PRO_COLLECTION_SOCIETY",
    supportedCodes: ["iswc", "ipi"],
    apiProtocol: "CWR_PROTOCOL",
    status: "ACTIVE",
  },
  {
    companyId: "EPIC_GAMES_STORE",
    name: "Epic Games / Unreal Marketplace",
    category: "GAME_PUBLISHER",
    supportedCodes: ["doi", "swid"],
    apiProtocol: "DIRECT_REST",
    status: "ACTIVE",
  },
  {
    companyId: "STEAM_VALVE",
    name: "Steam / Valve Corporation",
    category: "GAME_PUBLISHER",
    supportedCodes: ["doi", "swid"],
    apiProtocol: "DIRECT_REST",
    status: "ACTIVE",
  },
  {
    companyId: "EIDR_FILM_VAULT",
    name: "EIDR Global Film & TV Node",
    category: "FILM_DISTRIBUTOR",
    supportedCodes: ["isan", "eidr", "visan"],
    apiProtocol: "DIRECT_REST",
    status: "ACTIVE",
  },
  {
    companyId: "PHYSICAL_RFID_LEDGER",
    name: "Covenant Merch & RFID Smart Wearables",
    category: "MERCH_RETAILER",
    supportedCodes: ["epcRfid", "upc", "nilId"],
    apiProtocol: "ONCHAIN_LEDGER",
    status: "ACTIVE",
  },
];
